trigger:
  batch: true
  branches:
    include:
    - master

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: buildJob
        displayName: Build NuGets
        pool:
          vmImage: windows-latest
          demands:
          - MSBuild
        workspace:
          clean: all
        steps:
          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              useGlobalJson: true

          - task: NuGetCommand@2
            displayName: NuGet Restore
            inputs:
              command: restore

          - task: DotNetCoreCLI@2
            displayName: 'DotNet Build'
            inputs:
              command: build
              projects: src/**/*.csproj
              configuration: Release

          - task: PublishPipelineArtifact@1
            inputs:
              artifact: 'nuget'
              targetPath: $(Build.ArtifactStagingDirectory)


  - stage: test
    displayName: Run Tests
    jobs:
      - job: unit_tests
        displayName: Unit Tests
        pool:
          vmImage: macOS-latest
          demands:
          - MSBuild
        workspace:
          clean: all
        steps:
          - task: UseDotNet@2
            displayName: Install .NET SDK
            inputs:
              useGlobalJson: true

          - task: NuGetCommand@2
            displayName: NuGet Restore
            inputs:
              command: restore

          - task: DotNetCoreCLI@2
            displayName: DotNet Test
            inputs:
              projects: tests/**/*.csproj
              testRunTitle: Unit Tests
              publishTestResults: true

      - job: android_uitest
        displayName: 'Android UI Tests'
        pool:
          vmImage: macOS-latest
          demands:
          - MSBuild
          - Xamarin.Android
          - JDK
          - AndroidSDK
        workspace:
          clean: all
        steps:
          - template: build/steps/run-uitests.yml
            parameters:
              projectPath: sample/TestApp.Android/TestApp.Android.csproj
              platform: Android

      - job: ios_uitest
        displayName: 'iOS UI Tests'
        pool:
          vmImage: macOS-latest
          demands:
          - MSBuild
        workspace:
          clean: all
        steps:
          - template: build/steps/run-uitests.yml
            parameters:
              projectPath: sample/TestApp.iOS/TestApp.iOS.csproj
              platform: iOS

  - stage: deploy
    displayName: Deploy Artifacts
    condition: always()
    jobs:
      - deployment: sponsorConnect
        displayName: Sponsor Connect
        environment: Sponsor Connect
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: NuGet Push
                  inputs:
                    command: push
                    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg'
                    nuGetFeedType: external
                    publishFeedCredentials: SponsorConnect

      - deployment: nugetOrg
        displayName: 'NuGet.org'
        environment: NuGet
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NuGetCommand@2
                  displayName: NuGet Push
                  inputs:
                    command: push
                    packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg;$(Pipeline.Workspace)/**/*.snupkg'
                    nuGetFeedType: external
                    publishFeedCredentials: 'NuGet.org'